### ISSUE TITLE
Support jisho #based search syntax (Enhancement)

### ISSUE THREAD

**Issue by ghost** [JojiiOfficial/jisho-cli#1]
First of all, thanks for the tool. It's worlds faster than the other jisho-cli js-based version! 本当に助かりますよ :)
It would be great if this could become a fully-featured alternative to visiting the site, and to that end, it would be great if you could get the #based search, e.g. #kanji, working completely. I don't know any rust, but if it was mostly simple, I would be amenable to learning the basics and helping out too!

**Comment by JojiiOfficial** [comment]
Yeah I thought about that as well. Although this can't replace the site completely. The API doesn't provide eg. example sentences iirc. But I agree, a few more features would be nice to have indeed. 
If you want to help with this project, どうぞ.

**Comment by JojiiOfficial** [comment]
I just rechecked and saw that the # based search is sadly not (yet) provided by their API. I already implemented the basic logic for #kanji search and I'll implement it when their API supports it. I'm closing this for now.

**Comment by ghost** [comment]
Example sentences are from tatoeba anyway, though (AFAIK) - so that got me checking if they have an API, which they don't, but they have a regularly updated CSV corpus (https://tatoeba.org/eng/downloads) which one could query if one wanted. Perhaps it would make sense to build a separate tool for doing this at some point! 
Also, I signed up for a Rust class next semester, so maybe I can sneak some contributions to this project in as my class project. :P
