### ISSUE TITLE
Cannot install jisho-cli

### ISSUE THREAD

**Issue by DecayingEagle** [JojiiOfficial/jisho-cli#5]
I am a noob at rust and i just need help, this isn't the first crate i cannot install. I am on windows. Ask me for any info u want

PS C:\Users\roza0> cargo install jisho-cli
    Updating crates.io index
  Downloaded jisho-cli v0.1.3
  Downloaded 1 crate (117.5 KB) in 0.78s
  Installing jisho-cli v0.1.3
  Downloaded adler v1.0.2
  Downloaded ansi_term v0.12.1
  Downloaded colored v2.0.0
  Downloaded atty v0.2.14
  Downloaded itoa v1.0.1
  Downloaded once_cell v1.10.0
  Downloaded sct v0.7.0
  Downloaded unicode-bidi v0.3.7
  Downloaded webpki v0.22.0
  Downloaded crc32fast v1.3.2
  Downloaded rustls v0.20.4
  Downloaded ureq v2.4.0
  Downloaded log v0.4.16
  Downloaded tinyvec_macros v0.1.0
  Downloaded chunked_transfer v1.4.0
  Downloaded percent-encoding v2.1.0
  Downloaded spin v0.5.2
  Downloaded lazy_static v1.4.0
  Downloaded base64 v0.13.0
  Downloaded serde v1.0.136
  Downloaded form_urlencoded v1.0.1
  Downloaded cfg-if v1.0.0
  Downloaded unicode-normalization v0.1.19
  Downloaded flate2 v1.0.22
  Downloaded untrusted v0.7.1
  Downloaded idna v0.2.3
  Downloaded matches v0.1.9
  Downloaded miniz_oxide v0.4.4
  Downloaded ryu v1.0.9
  Downloaded serde_json v1.0.79
  Downloaded url v2.2.2
  Downloaded webpki-roots v0.22.2
  Downloaded ring v0.16.20
  Downloaded 33 crates (6.9 MB) in 5.04s (largest was `ring` at 5.1 MB)
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling winapi v0.3.9
   Compiling cc v1.0.73
   Compiling untrusted v0.7.1
   Compiling spin v0.5.2
   Compiling tinyvec_macros v0.1.0
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling log v0.4.16
   Compiling libc v0.2.121
   Compiling crc32fast v1.3.2
   Compiling serde v1.0.136
   Compiling matches v0.1.9
   Compiling serde_json v1.0.79
   Compiling unicode-bidi v0.3.7
   Compiling adler v1.0.2
   Compiling rustls v0.20.4
   Compiling percent-encoding v2.1.0
   Compiling ryu v1.0.9
   Compiling itoa v1.0.1
   Compiling chunked_transfer v1.4.0
   Compiling base64 v0.13.0
   Compiling once_cell v1.10.0
   Compiling lazy_static v1.4.0
   Compiling tinyvec v1.5.1
   Compiling form_urlencoded v1.0.1
   Compiling miniz_oxide v0.4.4
   Compiling ring v0.16.20
   Compiling unicode-normalization v0.1.19
   Compiling flate2 v1.0.22
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `C:\Users\roza0\AppData\Local\Temp\cargo-installbHLX5n\release\build\ring-ade733a79f75fb62\build-script-build` (exit code: 101)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-pc-windows-gnu")
  HOST = Some("x86_64-pc-windows-gnu")
  CC_x86_64-pc-windows-gnu = None
  CC_x86_64_pc_windows_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-pc-windows-gnu = None
  CFLAGS_x86_64_pc_windows_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")

  --- stderr
  running "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-g3" "-DNDEBUG" "-c" "-oC:\\Users\\roza0\\AppData\\Local\\Temp\\cargo-installbHLX5n\\release\\build\\ring-5d1602ff4b915290\\out\\aes_nohw.o" "crypto/fipsmodule/aes/aes_nohw.c"
  thread 'main' panicked at 'failed to execute ["gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-g3" "-DNDEBUG" "-c" "-oC:\\Users\\roza0\\AppData\\Local\\Temp\\cargo-installbHLX5n\\release\\build\\ring-5d1602ff4b915290\\out\\aes_nohw.o" "crypto/fipsmodule/aes/aes_nohw.c"]: program not found', C:\Users\roza0\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.16.20\build.rs:653:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `jisho-cli v0.1.3`, intermediate artifacts can be found at `C:\Users\roza0\AppData\Local\Temp\cargo-installbHLX5n`

Caused by:
  build failed

**Comment by JojiiOfficial** [comment]
No idea about Windows. Looks like a program is missing. That's all I can guess
